openapi: 3.0.0
info:
  title: UF1465
  description: REST del Ejercicio 1465_2
  version: 1.0.0
servers:
  - url: 'http://localhost:8081/uf1465'
    description: Servidor REST Servletst
tags:
  - name: producto
    description: Productos
  - name: categoria
    description: categorías de productos
  
paths:
  '/api/productos':
    get:
      tags:
        - producto
      summary: Ver todos los productos con su categoría
      description: ""
      operationId: getAll
      
      responses:   
        '200':
          description: 'successful operation'
          content:
            application/json:
              schema:
                type: 'array'
                items:
                  $ref: '#/components/schemas/Producto' 
                  
components:
  requestBodies:    
    Producto:
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Producto"
      description: Producto
      required: true
      
  schemas:
    Producto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nombre:
          type: string
        precio:
          type: integer
          format: int64
        Categoria:
             $ref: "#/components/schemas/Categoria"     
    Categoria:
      type: object
      properties:
        id:
          type: integer
          format: int64 
        nombre:
          type: string